import { Property } from '@/types/property'

// Mock data for development/demo before backend is connected
export const mockProperties: Property[] = [
    {
        id: 300001,
        title: 'Casa à Venda Solar dos Ataides 2',
        description: '🏡 Imóvel à Venda – Solar dos Ataídes II\n\nConquiste seu espaço com conforto e praticidade em uma das regiões mais desejadas da cidade!',
        type: 'Casa',
        status: 'approved',
        purpose: 'Venda',
        price: 450000,
        priceSale: 450000,
        address: 'Rua SA 11',
        city: 'Rio Verde',
        state: 'GO',
        bairro: 'Solar dos Ataides 2',
        bedrooms: 2,
        bathrooms: 1,
        areaConstruida: 92,
        areaTerreno: 150,
        garageSpots: 2,
        images: [
            'https://res.cloudinary.com/duumnyera/image/upload/v1768596701/conectimovel/properties/nuiklohfmk7tk4kgxuzo.jpg',
            'https://res.cloudinary.com/duumnyera/image/upload/v1768596702/conectimovel/properties/obo1xrjk28fqpshv36ew.jpg',
            'https://res.cloudinary.com/duumnyera/image/upload/v1768596703/conectimovel/properties/aokhxamzvrqyor37foyq.jpg',
        ],
        createdAt: '2026-01-16T20:51:48Z',
    },
    {
        id: 330001,
        title: 'Lote de Esquina no Campos Elisios',
        description: 'Oportunidade\nLote de Esquina de frente a praça',
        type: 'Terreno',
        status: 'approved',
        purpose: 'Venda',
        price: 450000,
        priceSale: 450000,
        address: 'Rua Gerse Fonseca',
        city: 'Rio Verde',
        state: 'GO',
        bairro: 'Campos Elisios',
        areaTerreno: 432,
        images: [
            'https://res.cloudinary.com/duumnyera/image/upload/v1768771005/conectimovel/properties/zmoqi6bh23tjr8dooyqk.jpg',
            'https://res.cloudinary.com/duumnyera/image/upload/v1768771006/conectimovel/properties/dyfkziuwkgtofmuqno4f.jpg',
        ],
        createdAt: '2026-01-18T21:16:46Z',
    },
    {
        id: 330002,
        title: 'Área de Oportunidade',
        description: 'Área à Venda – Jardim Presidente\n\n- Excelente localização\n- Área útil: 2.119 m²\n- Ideal para empreendimentos, investimento ou uso estratégico.',
        type: 'Terreno',
        status: 'approved',
        purpose: 'Venda',
        price: 1500000,
        priceSale: 1500000,
        address: 'Rua 105',
        city: 'Rio Verde',
        state: 'GO',
        bairro: 'Jardim Presidente',
        areaTerreno: 2769,
        images: [
            'https://res.cloudinary.com/duumnyera/image/upload/v1768771216/conectimovel/properties/yzakpsrjk9pygee0lxab.jpg',
            'https://res.cloudinary.com/duumnyera/image/upload/v1768771217/conectimovel/properties/g8m1b3c2r4j83yqoo9hv.jpg',
        ],
        videoUrl: 'https://res.cloudinary.com/duumnyera/video/upload/v1768771218/conectimovel/videos/lq4qupipwbeirgd0def4.mp4',
        createdAt: '2026-01-18T21:20:18Z',
    },
    {
        id: 330003,
        title: 'Casa no Canaã 2',
        description: 'Imóvel possui:\nGaragem para 2 veículos\nSala com o pé direito alto e com lustre\nPossui 3 quartos sendo 1 suíte\nRica em armários\nÁrea Gourmet com churrasqueira',
        type: 'Casa',
        status: 'approved',
        purpose: 'Venda',
        price: 790000,
        priceSale: 790000,
        address: 'Rua Professor Geraldo Mendonça',
        city: 'Rio Verde',
        state: 'GO',
        bairro: 'Residencial Canaã 2',
        bedrooms: 3,
        bathrooms: 3,
        areaConstruida: 126,
        areaTerreno: 180,
        garageSpots: 2,
        hasWifi: true,
        temArCondicionado: true,
        ehMobiliada: true,
        images: [
            'https://res.cloudinary.com/duumnyera/image/upload/v1768771936/conectimovel/properties/qjadqme6o8p9e2rxqxee.jpg',
            'https://res.cloudinary.com/duumnyera/image/upload/v1768771937/conectimovel/properties/wadlhojtyolyxew5t4j9.jpg',
            'https://res.cloudinary.com/duumnyera/image/upload/v1768771937/conectimovel/properties/uoigugb1xecnh6a6ill5.jpg',
        ],
        videoUrl: 'https://res.cloudinary.com/duumnyera/video/upload/v1768771941/conectimovel/videos/dvsrchinzcw9v0tjgggn.mp4',
        createdAt: '2026-01-18T21:32:23Z',
    },
    {
        id: 330004,
        title: 'Apartamento Centro',
        description: 'Apartamento moderno no centro da cidade com excelente localização.',
        type: 'Apartamento',
        status: 'approved',
        purpose: 'Aluguel',
        price: 2500,
        priceRent: 2500,
        address: 'Av. Presidente Vargas',
        city: 'Rio Verde',
        state: 'GO',
        bairro: 'Centro',
        bedrooms: 2,
        bathrooms: 1,
        areaConstruida: 70,
        garageSpots: 1,
        valorCondominio: 400,
        images: [
            'https://res.cloudinary.com/duumnyera/image/upload/v1768771936/conectimovel/properties/qjadqme6o8p9e2rxqxee.jpg',
        ],
        createdAt: '2026-01-20T10:00:00Z',
    },
    {
        id: 330005,
        title: 'Sobrado Alto Padrão',
        description: 'Sobrado de alto padrão com acabamento premium e piscina.',
        type: 'Casa',
        status: 'approved',
        purpose: 'Venda e Aluguel',
        price: 1200000,
        priceSale: 1200000,
        priceRent: 8000,
        address: 'Rua das Flores',
        city: 'Rio Verde',
        state: 'GO',
        bairro: 'Jardim Europa',
        bedrooms: 4,
        bathrooms: 4,
        areaConstruida: 280,
        areaTerreno: 400,
        garageSpots: 3,
        temPiscina: true,
        temEnergiaSolar: true,
        temAutomacao: true,
        temArCondicionado: true,
        ehMobiliada: true,
        images: [
            'https://res.cloudinary.com/duumnyera/image/upload/v1768596701/conectimovel/properties/nuiklohfmk7tk4kgxuzo.jpg',
        ],
        createdAt: '2026-01-25T14:30:00Z',
    },
]

export function getMockFeaturedProperties(): Property[] {
    return mockProperties.slice(0, 4)
}

export function getMockRecentProperties(): Property[] {
    return [...mockProperties].sort(
        (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
    )
}
